### ISSUE TITLE
Package external dependencies

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Apps-cli#26] opened 2018-08-08 08:20 UTC
There is no way to bundle external npm dependencies.

**Comment by kaiiiiiiiii** [comment] 2018-08-08 10:41
Duplicate of https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/49

**Comment by graywolf336** [comment] 2018-08-08 14:45
Closing as a result of duplicate of RocketChat/Rocket.Chat.Apps-ts-definition#49

**Closed by graywolf336** 2018-08-08 14:45 UTC
