### ISSUE TITLE
Unable to create app

### ISSUE THREAD

**Issue by jayjlow** [RocketChat/Rocket.Chat.Apps-cli#53] opened 2019-10-11 21:11 UTC
Receiving error when attempting to run command: rc-apps create

`~/Projects/Rocket.Chat Apps$ rc-apps create
Let's get started creating your app.
We need some information first:

   App Name: example
   App Description: example
   Author's Name: example
   Author's Home Page: example
   Author's Support Page: example

Creating a Rocket.Chat App in /Projects/Rocket.Chat Apps/example... !
TypeError: Cannot read property 'message' of undefined
    at Create.catch (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:86:18)
    at Create._run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:48:29)`

`rc-apps -v

@rocket.chat/apps-cli/1.5.1 linux-x64 node-v10.16.3`

**Comment by graywolf336** [comment] 2019-10-17 23:51
Closing as I have not been able to replicate this.

`@rocket.chat/apps-cli/1.5.1 darwin-x64 node-v12.12.0`

<img width="939" alt="Screen Shot 2019-10-17 at 6 46 08 PM" src="https://user-images.githubusercontent.com/850391/67055660-9a2d3180-f10e-11e9-8a49-412402651cf6.png">

But I went ahead and pushed a commit to hopefully avoid the issue, but I'm not sure what the root cause of the error that it tried to display was. https://github.com/RocketChat/Rocket.Chat.Apps-cli/commit/dc814db21650380190298dfb7a0593614c7dae97

**Closed by graywolf336** 2019-10-17 23:51 UTC

**Comment by zjadir** [comment] 2020-04-09 15:53
Had the same problem, solved it by running the following command : `npm install --save-dev @types/node`
